### ISSUE TITLE
ISO code and Glottolog code for language Bodo incorrectly assigned

### ISSUE THREAD

**Issue by Bibiko** [google-research-datasets/uninum#15]
Language "Bodo" (line 23 in [codes.tsv](https://github.com/google-research-datasets/uninum/blob/master/codes.tsv#L23)) refers to ISO code [brx](https://www.ethnologue.com/language/brx) and Glottolog code [bodo1269](https://glottolog.org/resource/languoid/id/bodo1269).

**Comment by kylebgorman** [comment]
Good catch: it looks like our table mapping from our internal codes to ISO 639-3 codes had an error and we confused this with a Niger-Congo language of the same name. Could I get your thumbs-up/+1 on pull request #17 just to make sure I did the right thing there @Bibiko?

**Comment by Bibiko** [comment]
This looks good to me - thanks. With the [PR](https://github.com/google-research-datasets/uninum/pull/17) we can closed this issue.
