### ISSUE TITLE
Glottolog code for Konkani (ISO kok) does not exist anymore

### ISSUE THREAD

**Issue by Bibiko** [google-research-datasets/uninum#16]
ISO code [kok](https://iso639-3.sil.org/code/kok) refers to a macro language that is divided into 

ISO [gom](https://iso639-3.sil.org/code/gom), Glottolog [goan1235](https://glottolog.org/resource/languoid/id/goan1235) Goan Konkani 
and 
ISO [knn](https://iso639-3.sil.org/code/knn), Glottolog [konk1267](https://glottolog.org/resource/languoid/id/konk1267) Konkan Marathi.

Glottocode konk1270 was removed a few versions ago for better knowledge.

**Comment by kylebgorman** [comment]
What do you think would be an appropriate edit? I don't have information about whether this data is better described as `knn`/`konk1267` or `gom`/`goan1235`.

**Comment by Bibiko** [comment]
I asked a colleague of mine who is more familiar with these languages. In short, if it's necessary to assign one of the varieties, then you can use goan1235 (gom). Both varieties are in terms of numerals really very similar (only the pronunciation differs). Another possibility would be to keep the ISO code `kok` (it's still valid as macro language) and assign both Glottocodes.

**Comment by kylebgorman** [comment]
Okay, I tried the former route in #18. Please LGTM if it looks okay to you.

**Comment by Bibiko** [comment]
It looks good to me too. Thanks.
