### ISSUE TITLE
Language code mappings and file mappings, 1000000000000

### ISSUE THREAD

**Issue by chrzyki** [google-research-datasets/uninum#5]
Thank you again for this very helpful collection!

While working with the data, a couple of issues arose:

- https://github.com/google/uninum/blob/master/numbers/est.tsv appears to be the only language with an entry for `1000000000000`, was that intended?
- Code `ary_no_diacritics`, `ary_with_diacritics`, `arz`, and `bho` in https://github.com/google/uninum/blob/master/codes.tsv don't seem to have any immediately obvious correspondence to the number tables. 
- https://github.com/google/uninum/blob/master/numbers/arx.tsv (i.e. the code `arx`) is not represented in the codes table

Sorry if there are obvious connections that I just missed!

**Comment by kylebgorman** [comment]
On Fri, Oct 25, 2019 at 4:44 AM Christoph Rzymski <notifications@github.com>
wrote:

> Thank you again for this very helpful collection!
>
> While working with the data, a couple of issues arose:
>
>    - https://github.com/google/uninum/blob/master/numbers/est.tsv appears
>    to be the only language with an entry for 1000000000000, was that
>    intended?
>
>
This is as intended. We include whatever we have in our internal data.

>
>    - Code ary_no_diacritics, ary_with_diacritics, arz, and bho in
>    https://github.com/google/uninum/blob/master/codes.tsv don't seem to
>    have any immediately obvious correspondence to the number tables.
>    - https://github.com/google/uninum/blob/master/numbers/arx.tsv (i.e.
>    the code arx) is not represented in the codes table
>
>
This sounds like an actual omission. Pinging a colleague to take a look at
this.

Sorry if there are obvious connections that I just missed!

**Comment by chrzyki** [comment]
Thanks for the clarification and for checking!

**Comment by kylebgorman** [comment]
Going to split this into several issues.
